version: '3.2'
services:
  node:
    build: ./
    entrypoint: dockerize -wait tcp://app-db:27017 -timeout 20s docker-entrypoint.sh
    ports:
      - "3333:8080"
    depends_on:
      - app-db
    env_file:
      - ./.env
    networks:
      - gateway
    volumes:
      - ./:/usr/src/app
    command: >
      bash -c "npm install && npm run build && npm start"
    links: 
      - app-db
    tty: true
  app-db:
    image: mongo:5.0
    ports:
      - 27017:27017
    networks:
      - gateway
    volumes:
      - ~/apps/mongo:/data/db
    env_file:
      - ./.env
  botpress:
    image: botpress/server:latest
    volumes:
      - /botpress/data:/data/botpress
    ports:
      - 3333:3000
    networks:
      - gateway
networks:
  gateway: {}