apiVersion: apps/v1
kind: Deployment
metadata:
  name: "omniserver"
  labels:
    app: "omniserver"
spec:
  selector:
    matchLabels:
      app: "omniserver"
  replicas: 10
  template:
    metadata:
      labels:
        app: "omniserver"
    spec:
      containers:
        - name: "node"
          image: "israelmarmar/omni_backend_node:latest"
          resources:
            requests:
              cpu: 100m
        - name: "db"
          image: "israelmarmar/omni_db:latest"
          resources:
            requests:
              cpu: 100m
        - name: "botpress"
          image: "israelmarmar/omni_botpress:latest"
          resources:
            requests:
              cpu: 100m